[package]
name = "cyproto-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"] }
heapless= { version = "0.7" }

[build-dependencies]
cbindgen = "0.24"
